version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html
      - /var/www/html/node_modules
      - /var/www/html/vendor
    ports:
      - "8000:80"
    depends_on:
      - db
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=hire_wire
      - DB_USERNAME=hire_wire_user
      - DB_PASSWORD=password

  db:
    image: mariadb:10.11
    environment:
      - MYSQL_DATABASE=hire_wire
      - MYSQL_USER=hire_wire_user
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./docker/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"
    command: >
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
      --innodb-buffer-pool-size=64M
      --innodb-log-file-size=32M
      --innodb-log-buffer-size=8M

volumes:
  mariadb_data:
